spring:
  application:
    name: config
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/porcelani/microservices
          searchPaths: config-repo

---

spring:
    profiles: docker