spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/porcelani/microservices
          searchPaths: config-repo
server:
  port: 8888

---

spring:
    profiles: docker