version: '2'
services:
  cassandra:
    container_name: cassandra
    image: spotify/cassandra
    ports:
      - "9160:9160"
      - "9042:9042"
  admin:
    container_name: admin
    image: aetas/spring-boot-admin-docker:1.4.1
    ports:
      - "8762:8080"
  eureka:
    container_name: eureka
    build: ./eureka
    ports:
      - "8761:8761"
  config:
    container_name: config
    build: ./config
    ports:
      - "8888:8888"
  zuul:
    container_name: zuul
    build: ./zuul
    ports:
      - "80:8080"