eureka:
    instance:
        hostname: localhost
    client:
        registerWithEureka: false
        fetchRegistry: false
    serviceUrl:
        defaultZone: http://${eureka.instace.hostname}:${server.port}/eureka
spring:
    boot:
        admin:
            url: http://localhost:8762

---

spring:
    profiles: docker
    boot:
        admin:
           url: http://admin:8080
