eureka:
    instance:
        hostname: localhost
    client:
        registerWithEureka: false
        fetchRegistry: false
    serviceUrl:
        defaultZone: http://${eureka.instace.hostname}:${server.port}/eureka
---

spring:
    profiles: docker

