spring:
  application:
    name: edge
#  cloud:
#    config:
#      uri: http://localhost:8888
server:
  port: 8070

---

spring:
    profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
